Update nextjs.yml
Signed-off-by: AU_gdev_19 <64915515+Dargon789@users.noreply.github.com>

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -88,6 +88,13 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v4
+      - name: Install dependencies
+        run: |
+            if [ -f "yarn.lock" ]; then
+            yarn install
+            elif [ -f "package-lock.json" ]; then
+            npm ci
+            else
+            echo "Unable to determine package manager"
+            exit 1
+            fi
